// src/pages/Home.js
import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import '../styles/home.css';

const Home = () => {
  const { currentUser, userProfile } = useAuth();

  return (
    <div className="home-container">
      <div className="hero-section">
        <h1>Welcome to VIT Education Portal</h1>
        <p>Your gateway to interactive learning and knowledge assessment</p>
        {currentUser ? (
          <div className="user-welcome">
            <h2>Welcome back, {currentUser.email.split('@')[0]}</h2>
            <div className="action-buttons">
              <Link to="/courses" className="action-button">
                Explore Courses
              </Link>
              <Link to="/quizzes" className="action-button secondary">
                Take Quizzes
              </Link>
            </div>
          </div>
        ) : (
          <div className="action-buttons">
            <Link to="/register" className="action-button">
              Register Now
            </Link>
            <Link to="/login" className="action-button secondary">
              Login
            </Link>
          </div>
        )}
      </div>

      <div className="features-section">
        <h2>Key Features</h2>
        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon">📚</div>
            <h3>Interactive Courses</h3>
            <p>Access a wide range of courses with integrated YouTube videos from expert educators.</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">🧠</div>
            <h3>AI-Powered Quizzes</h3>
            <p>Test your knowledge with dynamic quizzes generated by OpenAI based on your chosen topics.</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">📈</div>
            <h3>Progress Tracking</h3>
            <p>Monitor your learning journey with detailed progress tracking for each course.</p>
          </div>
          <div className="feature-card">
            <div className="feature-icon">🏆</div>
            <h3>Achievements</h3>
            <p>Earn certificates and badges as you complete courses and excel in quizzes.</p>
          </div>
        </div>
      </div>

      <div className="subjects-section">
        <h2>Popular Subjects</h2>
        <div className="subjects-grid">
          <div className="subject-card">
            <h3>Computer Science</h3>
            <ul>
              <li>Programming Fundamentals</li>
              <li>Data Structures & Algorithms</li>
              <li>Web Development</li>
              <li>Artificial Intelligence</li>
            </ul>
          </div>
          <div className="subject-card">
            <h3>Mathematics</h3>
            <ul>
              <li>Calculus</li>
              <li>Linear Algebra</li>
              <li>Probability & Statistics</li>
              <li>Discrete Mathematics</li>
            </ul>
          </div>
          <div className="subject-card">
            <h3>Physics</h3>
            <ul>
              <li>Classical Mechanics</li>
              <li>Electromagnetism</li>
              <li>Thermodynamics</li>
              <li>Quantum Physics</li>
            </ul>
          </div>
          <div className="subject-card">
            <h3>Engineering</h3>
            <ul>
              <li>Mechanical Engineering</li>
              <li>Electrical Engineering</li>
              <li>Civil Engineering</li>
              <li>Chemical Engineering</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
